# Generated by Django 5.2 on 2025-05-12 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=7)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
            ],
        ),
    ]
