# Generated by Django 5.2 on 2025-05-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address'),
        ),
    ]
