# Generated by Django 5.2 on 2025-05-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='address_id',
            new_name='address',
        ),
    ]
